config/routes.rb
Rails.application.routes.draw do

  resources :specializations

  resources :medical_consultations

  resources :doctors

  root 'welcome#index'

  resources :users

  get  "users/index"
  get  "/login"           => "users#login"
  post "/signin"          => "users#authenticate"
  get  "/signup"          => "users#new"
  get  "/logout"          => "users#logout"
  get  "/password"        => "users#password"
  post "/password_update" => "users#password_update"
end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  validates_presence_of   :description
  validates_uniqueness_of :description
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  before_action :set_specialization, only: [:show, :edit, :update, :destroy]

  # GET /specializations
  # GET /specializations.json
  def index
    @specializations = Specialization.all
  end

  # GET /specializations/new
  def new
    @specialization = Specialization.new
  end

  # GET /specializations/1/edit
  def edit
  end

  # POST /specializations
  # POST /specializations.json
  def create
    @specialization = Specialization.new(specialization_params)

    respond_to do |format|
      if @specialization.save
        format.html { redirect_to @specialization, notice: 'Specialization was successfully created.' }
        format.json { render :show, status: :created, location: @specialization }
      else
        format.html { render :new }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specializations/1
  # PATCH/PUT /specializations/1.json
  def update
    respond_to do |format|
      if @specialization.update(specialization_params)
        format.html { redirect_to @specialization, notice: 'Specialization was successfully updated.' }
        format.json { render :show, status: :ok, location: @specialization }
      else
        format.html { render :edit }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specializations/1
  # DELETE /specializations/1.json
  def destroy
    @specialization.destroy
    respond_to do |format|
      format.html { redirect_to specializations_url, notice: 'Specialization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialization
      @specialization = Specialization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialization_params
      params.require(:specialization).permit(:description)
    end
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/specializations/_form.html.erb
<%= form_for(@specialization) do |f| %>
  <% if @specialization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialization.errors.count, "error") %> prohibited this specialization from being saved:</h2>

      <ul>
      <% @specialization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specializations/edit.html.erb
<h1>Editing specialization</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialization %> |
<%= link_to 'Back', specializations_path %>

app/views/specializations/index.html.erb
<h1>Especializações</h1>

<div class="modulo">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Descrição</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @specializations.each do |specialization| %>
        <tr>
          <td><%= specialization.description %></td>
          <td><%= link_to t('edit'), edit_specialization_path(specialization) %></td>
          <td><%= link_to t('destroy'), specialization, method: :delete, data: { confirm: t('are_you_sure') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Nova Especialização', new_specialization_path %>

app/views/specializations/new.html.erb
<h1>New specialization</h1>

<%= render 'form' %>

<%= link_to 'Back', specializations_path %>