config/routes.rb
Rails.application.routes.draw do

  resources :specializations

  resources :medical_consultations

  resources :doctors

  root 'welcome#index'

  resources :users

  get  "users/index"
  get  "/login"           => "users#login"
  post "/signin"          => "users#authenticate"
  get  "/signup"          => "users#new"
  get  "/logout"          => "users#logout"
  get  "/password"        => "users#password"
  post "/password_update" => "users#password_update"
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base

  validates_presence_of   :name, :email, :crm_number
  validates_uniqueness_of :name, :email, :crm_number

  has_and_belongs_to_many :specializations
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @specializations = Specialization.all.map(&:description)
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
    @specializations = Specialization.all
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :email, :website, :crm_number, :address, :phone1, :phone2, :comments)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :specialization %><br>
    <%= f.select :specialization_ids, Specialization.all.collect {|x| [x.description, x.id]}, {}, { multiple: true} %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :crm_number %><br>
    <%= f.number_field :crm_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br>
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br>
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Edição de médico</h1>

<%= render 'form' %>

<%= link_to t('back'), doctors_path %>

app/views/doctors/index.html.erb
<h1>Médicos</h1>
<div class="modulo">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Especializações</th>
        <th>Email</th>
        <th>Website</th>
        <th>CRM</th>
        <th>Endereço</th>
        <th>Tel 1</th>
        <th>Tel 2</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.name %></td>
          <td><%= doctor.specializations.collect(&:description).join(",") %></td>
          <td><%= doctor.email %></td>
          <td><%= doctor.website %></td>
          <td><%= doctor.crm_number %></td>
          <td><%= doctor.address %></td>
          <td><%= doctor.phone1 %></td>
          <td><%= doctor.phone2 %></td>
          <td><%= link_to t('edit'), edit_doctor_path(doctor) %></td>
          <td><%= link_to t('destroy'), doctor, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @doctor.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @doctor.website %>
</p>

<p>
  <strong>Crm number:</strong>
  <%= @doctor.crm_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>Phone1:</strong>
  <%= @doctor.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @doctor.phone2 %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @doctor.comments %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>